### ISSUE TITLE
Can't install plugin-authenticator v2.1.0 with Syspass 3.1.2 docker image

### ISSUE THREAD

**Issue by 9numbernine9** [sysPass/plugin-Authenticator#28]
Hello!

I'm trying to use the authenticator plugin in a `docker-compose` setup with Syspass `3.1.2`. Based on the `docker-compose.yml` file in the documentation, it looks like this:

```
version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.1.2
    restart: always
    ports:
      - "80"
      - "443"
    links:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    environment:
      - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^2.1
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
```
During startup of the `syspass-app` container, however, I see log messages like these:
```
syspass-app | setup_composer_extensions: syspass/plugin-authenticator:^2.1
syspass-app | ~ /var/www/html
syspass-app | run_composer: Running composer
syspass-app | ./composer.json has been updated
syspass-app | Loading composer repositories with package information
syspass-app | Updating dependencies
syspass-app | Your requirements could not be resolved to an installable set of packages.
syspass-app | 
syspass-app |   Problem 1
syspass-app |     - The requested package phpseclib/phpseclib (locked at 2.0.21, required as ~2.0.25) is satisfiable by phpseclib/phpseclib[2.0.21] but these conflict with your requirements or minimum-stability.
syspass-app |   Problem 2
syspass-app |     - The requested package php-di/php-di (locked at 6.0.9, required as ~6.0.11) is satisfiable by php-di/php-di[6.0.9] but these conflict with your requirements or minimum-stability.
syspass-app | 
syspass-app | Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
syspass-app | 
syspass-app | Installation failed, reverting ./composer.json to its original content.
```
It seems like the dependencies specified in either `composer.json` or `composer.lock` don't agree with each other between the authenticator and Syspass itself?

What's interesting is that if I switch to version `3.1.1` of Syspass (`image: syspass/syspass:3.1.1`), everything seems to work fine:
```
syspass-app | setup_composer_extensions: syspass/plugin-authenticator:^2.1
syspass-app | ~ /var/www/html
syspass-app | run_composer: Running composer
syspass-app | ./composer.json has been updated
syspass-app | Loading composer repositories with package information
syspass-app | Updating dependencies
syspass-app | Package operations: 3 installs, 0 updates, 0 removals
syspass-app |   - Installing syspass/extension-installer-plugin (dev-master 84775dd): Cloning 84775ddce1 from cache
syspass-app |   - Installing bacon/bacon-qr-code (1.0.3): Downloading (100%)         
syspass-app |   - Installing syspass/plugin-authenticator (v2.1.0): Downloading (100%)         
syspass-app | Package jeremeamia/SuperClosure is abandoned, you should avoid using it. Use opis/closure instead.
syspass-app | Writing lock file
syspass-app | Generating optimized autoload files
syspass-app | /var/www/html
```

Would it be possible to update the authenticator plugin and release a new version that's compatible with the Syspass `3.1.2` release?
